AWSTemplateFormatVersion: "2010-09-09"

Description: This template create a VPC called DevOps1 with CIDR 10.0.0.0/24

Parameters:
  Environment:
    Description: Define the Environment
    Type: String
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    MinLength: 5
    MaxLength: 12
    ConstraintDescription: Name must start with a letter and followed by any letter or number, minimum lenght 5 and maximun lenght 12
  VPCName:
    Description: Define the VPCName
    Type: String
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    MinLength: 5
    MaxLength: 12
    ConstraintDescription: Name must start with a letter and followed by any letter or number, minimum lenght 5 and maximun lenght 12
  CIDR:
    Description: Define CIDR
    Type: String
    Default: 10.0.0.0/16
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref CIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      -
        Key: Name
        Value: !Ref VPCName
      - 
        Key: Environment
        Value: !Ref Environment

Outputs:
  myVPC: 
    Description: A reference to the created VPC
    Value: !Ref myVPC
  CIDR:
    Description: CIDR of the VPC
    Value: !GetAtt myVPC.CidrBlock 
